// <auto-generated />
using System;
using BugTraq.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BugTraq.Api.Migrations
{
    [DbContext(typeof(BugTraqContext))]
    partial class BugTraqContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("BugTraq.Api.Models.Bug", b =>
                {
                    b.Property<int>("BugId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<int>("UserId");

                    b.HasKey("BugId");

                    b.HasIndex("UserId");

                    b.ToTable("Bugs");

                    b.HasData(
                        new
                        {
                            BugId = 1,
                            CreatedDate = new DateTime(2019, 2, 14, 1, 32, 24, 550, DateTimeKind.Local).AddTicks(4160),
                            Description = "Change the logo on the website",
                            Status = "Open",
                            Title = "Add new company logo to website",
                            UserId = 1
                        },
                        new
                        {
                            BugId = 2,
                            CreatedDate = new DateTime(2019, 2, 14, 1, 32, 24, 555, DateTimeKind.Local).AddTicks(1700),
                            Description = "Create an automated backup process",
                            Status = "Open",
                            Title = "Create a backup process",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BugTraq.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FirstName = "Jeff",
                            Surname = "Simms"
                        },
                        new
                        {
                            UserId = 2,
                            FirstName = "Sally",
                            Surname = "Prescott"
                        });
                });

            modelBuilder.Entity("BugTraq.Api.Models.Bug", b =>
                {
                    b.HasOne("BugTraq.Api.Models.User", "User")
                        .WithMany("Bugs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
